version: 1.{build}

clone_folder: c:\projects\pping
os: Visual Studio 2015
platform: x64
configuration: Release

before_build:
    - echo Running cmake...
    - cd c:\projects\pping
    - cmake -G "Visual Studio 14 2015 Win64"

build:
    project: ALL_BUILD.vcxproj

test_script:
    - ctest --output-on-failure -C Release
